<?php

/**
 * Implements hook_menu().
 */function drupal_api_menu(){
  $items=array();
  $items['api/get-jobs'] = array(
    'page callback' => 'jobs_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-employers'] = array(
    'page callback' => 'employer_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-applications'] = array(

    'page callback' => 'application_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function jobs_page_callback() {

  $results = [];
  $params = drupal_get_query_parameters();
  $emp_id = $params['employer_id'];//test ID =0/1
  $encodedkey = $params['api_key'];//test 2

  $start_date =$params['start_date'];
  $starttimestamp = strtotime($start_date);

  $end_date = $params['end_date'];
  $endtimestamp = strtotime($end_date);

  $hasKey = db_select('field_data_field_portal_api_key');
  $hasKey->addField('field_data_field_portal_api_key', 'field_portal_api_key_value');
  $hasKey->condition('field_portal_api_key_value', $encodedkey);
  $key = $hasKey->execute()->fetchField();

  if ($key == $encodedkey) {
    if (isset($emp_id)) {
      // no need to query twice here can get all data by single query
      //provides a response with all jobs for that particular node id
      $query = db_select('node', 'n');
      $query->join('node_expire', 'ne', 'n.nid=ne.nid');
      $query->addField('n', 'nid', 'nid');
      $query->addField('n', 'title', 'title');
      $query->addField('n', 'created', 'created');
      $query->addField('n', 'status', 'status');
      $query->addField('ne', 'expire', 'expire');
      $query->condition('n.uid', $emp_id);
      $query->condition('created', array($starttimestamp,$endtimestamp), 'BETWEEN');
      $data = $query->execute()->fetchAll();

      foreach ($data as $row) {

        $obj = [];
        $obj['nid'] = $row->nid;
        $obj['title'] = $row->title;
        $obj['created'] = $row->created;
        $obj['status'] = $row->status;
        $obj['expire'] = $row->expire;
        $obj['url'] = url("node/$row->nid");
        array_push($results, $obj);

      }

      return drupal_json_output($results);
    }
    else {
      http_response_code(412);
    }
  }
  else {
    http_response_code(401);
  }


}

function employer_page_callback() {

  $results = array();
  $params=drupal_get_query_parameters();
  $encodedkey=$params['api_key'];//test 2

  $hasKey = db_select('field_data_field_portal_api_key');
  $hasKey->addField('field_data_field_portal_api_key', 'field_portal_api_key_value');
  $hasKey->condition('field_portal_api_key_value',$encodedkey);
  $key = $hasKey->execute()->fetchField();

  if($key==$encodedkey) {

    //get ID's relevant to employer- get user ID where role ID is 4
    $isEmployer = db_select('users_roles');
    $isEmployer->addField('users_roles', 'uid');
    $isEmployer->condition('rid', 4);
    $employerID = $isEmployer->execute()->fetchCol();

    //get employer Data
    $query = db_select('users');
    $query->addField('users', 'uid','uid');
    $query->addField('users', 'name','name');
    $query->addField('users', 'mail','mail');
    $query->addField('users', 'picture','picture');
    $query->condition('uid', $employerID);

    $data = $query->execute()->fetchAll();
    $response = [
      'employers' => []
    ];

    foreach ($data as $row) {

      $file = file_load($row->picture);
      $uri = $file->uri;
      $url = file_create_url($uri);

      $obj = [];
      $obj['uid'] = $row->uid;
      $obj['name'] = $row->name;
      $obj['mail'] = $row->mail;
      $obj['picture'] = $url;
      array_push($response['employers'], $obj);

    }

    return drupal_json_output($response);
  }
  else
  {

    http_response_code(401);

  }

}

function application_page_callback() {
  $results = [];
  $params = drupal_get_query_parameters();
  $job_id = $params['job_id']; //valid job ID =15939,15884,15870
  $encodedkey = $params['api_key'];//test 2

  $start_date =$params['start_date'];
  $starttimestamp = strtotime($start_date);

  $end_date = $params['end_date'];
  $endtimestamp = strtotime($end_date);

  $hasKey = db_select('field_data_field_portal_api_key');
  $hasKey->addField('field_data_field_portal_api_key', 'field_portal_api_key_value');
  $hasKey->condition('field_portal_api_key_value', $encodedkey);
  $key = $hasKey->execute()->fetchField();

  if ($key == $encodedkey) {
    if (isset($job_id)) {
      $query = db_select('webform_submitted_data');
      $query->addField('webform_submitted_data', 'sid');
      $query->condition('nid', 15); /*Node ID 15 specifies all the submissions related to jobs*/
      $query->condition('data', $job_id);
      $query->condition('cid', 10);
      $setofsid = $query->execute()->fetchAll();

      if ($setofsid) {

        foreach ($setofsid as $sid) {

          $querySubmissions = db_select('webform_submitted_data', 'wsd');
          $querySubmissions->join('webform_submissions', 'sd', 'sd.sid=wsd.sid');
          $querySubmissions->leftJoin('webform_component', 'wc', 'wsd.cid = wc.cid');
          $querySubmissions->addField('wsd', 'data');
          $querySubmissions->addField('wsd', 'sid');
          $querySubmissions->addField('wc', 'name');
          $querySubmissions->condition('wsd.sid', $sid->sid);
          $querySubmissions->condition('sd.sid', $sid->sid);
          $querySubmissions->condition('submitted', array($starttimestamp,$endtimestamp), 'BETWEEN');
          $querySubmissions->groupBy('wsd.data');
          $result = $querySubmissions->execute()->fetchAll();


          foreach ($result as $row) {

            if ($row->name == 'Attach your CV') {
              $file = file_load($row->data);
              $obj[$row->name] = file_create_url($file->uri);
            }
            else if($row->name != 'Attach your CV') {
              $obj['id'] = $row->sid;
              $obj[$row->name] = $row->data;

            }
          }
          array_push($results, $obj);
        }



      }
      if($obj == NULL)
      {
        $empty=[
          "applications:"=>[]
        ];
        return drupal_json_output($empty);
      }else
      {
        return drupal_json_output($results);
      }

    }
    else {
      http_response_code(412);
    }
  }
  else {
    http_response_code(401);
  }

}
?>
