<?php

/*
 *
 * This function is responsible common,resused functions
 */
class common {
  public $ridVal;
  public $nidVal;
  public $cidVal;
  public $coursenidVal;
  public $coursecidVal;
  public $courseridVal;


  /*
   * Get Node ID containing webforms related to job
  */
  function get_nid() {
    $query = db_select('api_configuration');
    $query->addField('api_configuration', 'nid');
    $nidValOutput = $query->execute()->fetchField();
    $this->nidVal = $nidValOutput;

    return $this->nidVal;
  }

 /*
 * Get content ID to identify application data
 */
  function get_cid() {
    $query = db_select('api_configuration');
    $query->addField('api_configuration', 'cid');
    $cidValOutput = $query->execute()->fetchField();
    $this->cidVal = $cidValOutput;

    return $this->cidVal;
  }

  /*
  * Get Role ID relevant employers
  */
  function get_rid() {
    $query = db_select('api_configuration');
    $query->addField('api_configuration', 'rid');
    $ridValOutput = $query->execute()->fetchField();
    $this->ridVal = $ridValOutput;

    return $this->ridVal;
  }

  /*
   * Get Node ID containing webforms related to job
  */
  function get_course_nid() {
    $query = db_select('api_configuration');
    $query->addField('api_configuration', 'courses_nid');
    $coursenidValOutput = $query->execute()->fetchField();
    $this->coursenidVal = $coursenidValOutput;

    return $this->coursenidVal;
  }

  /*
  * Get content ID to identify application data
  */
  function get_course_cid() {
    $query = db_select('api_configuration');
    $query->addField('api_configuration', 'courses_cid');
    $coursecidValOutput = $query->execute()->fetchField();
    $this->coursecidVal = $coursecidValOutput;

    return $this->coursecidVal;
  }

  /*
  * Get content ID to identify application data
  */
  function get_course_rid() {
    $query = db_select('api_configuration');
    $query->addField('api_configuration', 'courses_rid');
    $courseridValOutput = $query->execute()->fetchField();
    $this->courseridVal = $courseridValOutput;

    return $this->courseridVal;
  }

  /*
   * Check if API key matches the key sent with request
   * */
  function authenticate() {
    $params = drupal_get_query_parameters();
    $encodedkey = $params['api_key'];

    $hasKey = db_select('api_configuration');
    $hasKey->addField('api_configuration', 'api_key');
    $key = $hasKey->execute()->fetchField();


    if ($key === $encodedkey) {
      return true;
    }
    else {
      return false;
    }
  }
}
/**
 * Implements hook_menu().
 * Menu including the endpoint URL and page callback
 *
 */function drupal_api_menu(){
  $items=array();
  $items['api/get-jobs'] = array(
    'page callback' => 'jobs_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-employers'] = array(
    'page callback' => 'employer_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-applications'] = array(
    'page callback' => 'application_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/summary'] = array(
    'page callback' => 'summary_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/development/drupal_api_settings'] = array(
    'title' => 'Drupal API settings',
    'description' => 'Configuration for Drupal API module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_api_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['api/study-overseas-data'] = array(
    'page callback' => 'overseas_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-course-providers'] = array(
    'page callback' => 'course_providers_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-courses'] = array(
    'page callback' => 'courses_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-inquires'] = array(
    'page callback' => 'course_inquiry_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/get-agents'] = array(
    'page callback' => 'agent_page_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * This function is to get job details posted by employers and filtered by
 * date range by providing "employer ID"
 */
function jobs_page_callback() {

  $results = [];
  $params = drupal_get_query_parameters();
  $emp_id = $params['employer_id'];

  $start_date =$params['start_date'];
  $starttimestamp = strtotime($start_date.'00:00:00');

  $end_date = $params['end_date'];
  $endtimestamp = strtotime($end_date.'23:59:59');

  $common=new common();
  if($common->authenticate() == TRUE){
    if (isset($emp_id)) {

      $query = db_select('node', 'n');
      $query->join('node_expire', 'ne', 'n.nid=ne.nid');
      $query->addField('n', 'nid', 'nid');
      $query->addField('n', 'title', 'title');
      $query->addField('n', 'created', 'created');
      $query->addField('n', 'status', 'status');
      $query->addField('ne', 'expire', 'expire');
      $query->condition('n.uid', $emp_id);
      $query->condition('created', array($starttimestamp), '>=');
      $query->condition('created', array($endtimestamp), '<=');
      $data = $query->execute()->fetchAll();

      foreach ($data as $row) {

        $obj = [];
        $obj['nid'] = $row->nid;
        $obj['title'] = $row->title;
        $obj['created'] = $row->created;
        $obj['status'] = $row->status;
        $obj['expire'] = $row->expire;
        $obj['url'] = url("node/$row->nid");
        array_push($results, $obj);

      }
      return drupal_json_output($results);
    }
    else {
      http_response_code(412);
    }
  }
  else {
    http_response_code(401);
  }


}

/*
 * This function is to get all the employer and details
 */
function employer_page_callback() {

  $common=new common();

  if($common->authenticate() == TRUE){


/*
 * get employer ID's relevant to employer
*/
    $isEmployer = db_select('users_roles');
    $isEmployer->addField('users_roles', 'uid');
    $isEmployer->condition('rid', $common->get_rid());
    $employerID = $isEmployer->execute()->fetchCol();

/*
 * employer Data
*/
    $query = db_select('users');
    $query->addField('users', 'uid','uid');
    $query->addField('users', 'name','name');
    $query->addField('users', 'mail','mail');
    $query->addField('users', 'picture','picture');
    $query->condition('uid', $employerID);

    $data = $query->execute()->fetchAll();
    $response = [
      'employers' => []
    ];

    foreach ($data as $row) {

      $file = file_load($row->picture);
      $url = file_create_url($file->uri);

      $obj = [];
      $obj['uid'] = $row->uid;
      $obj['name'] = $row->name;
      $obj['mail'] = $row->mail;
      $obj['picture'] = $url;
      array_push($response['employers'], $obj);

    }

    return drupal_json_output($response);
  }
  else
  {

    http_response_code(401);

  }

}

/*
 * This function is to get applications and details submitted for job offers
 * filtered by date range by providing "job ID"
*/
function application_page_callback() {
  $results = [];
  $params = drupal_get_query_parameters();
  $job_id = $params['job_id'];

  $start_date =$params['start_date'];
  $starttimestamp = strtotime($start_date.'00:00:00');

  $end_date = $params['end_date'];
  $endtimestamp = strtotime($end_date.'23:59:59');

  $common = new common();

  if($common->authenticate() == TRUE){
    if (isset($job_id)) {

      /*
       * Get application submissions
       */
      $query = db_select('webform_submitted_data');
      $query->addField('webform_submitted_data', 'sid');
      $query->condition('nid', $common->get_nid());
      $query->condition('data', $job_id);
      $query->condition('cid', $common->get_cid());
      $setofsid = $query->execute()->fetchAll();

      /*
       * Get taxonomy ID to identify the job industry
       */
      $query = db_select('field_data_field_industry');
      $query->addField('field_data_field_industry', 'field_industry_tid');
      $query->condition('entity_id', $job_id);
      $tid = $query->execute()->fetchAll();//get taxanomy ID

      foreach ($tid as $tidValue) {

        /*
         * Get industry name based on taxanomy ID
         */
        $query2 = db_select('taxonomy_term_data');
        $query2->addField('taxonomy_term_data', 'name');
        $query2->condition('tid', $tidValue->field_industry_tid);
        $result2 = $query2->execute()->fetchAll();
      }


      if ($setofsid) {

        foreach ($setofsid as $sid) {
          /*
           * Get all data relevant to application based on submission ID
           */
          $querySubmissions = db_select('webform_submitted_data', 'wsd');
          $querySubmissions->join('webform_submissions', 'sd', 'sd.sid=wsd.sid');
          $querySubmissions->leftJoin('webform_component', 'wc', 'wsd.cid = wc.cid');
          $querySubmissions->addField('wsd', 'data');
          $querySubmissions->addField('wsd', 'sid');
          $querySubmissions->addField('wc', 'name');
          $querySubmissions->condition('wsd.sid', $sid->sid);
          $querySubmissions->condition('sd.sid', $sid->sid);
          $querySubmissions->condition('submitted', array($starttimestamp), '>=');
          $querySubmissions->condition('submitted', array($endtimestamp), '<=');
          $querySubmissions->groupBy('wsd.data');
          $result = $querySubmissions->execute()->fetchAll();

          foreach ($result as $row) {

            if ($row->name == 'Attach your CV') {
              $file = file_load($row->data);
              $obj[$row->name] = file_create_url($file->uri);
            }
            else if($row->name != 'Attach your CV') {

              $obj['id'] = $row->sid;
              $obj[$row->name] = $row->data;
              foreach ($result2 as $jobCategory){
                $obj['job_category']=$jobCategory->name;
              }

            }
          }
          array_push($results, $obj);
        }

      }
      if($obj == NULL)
      {
        $empty=[
          "applications:"=>[]
        ];
        return drupal_json_output($empty);
      }else
      {
        return drupal_json_output($results);
      }

    }
    else {
      http_response_code(412);
    }
  }
  else {
    http_response_code(401);
  }

}

/*
 * This function is to get summary of jobs,applications and specific URL
 * filtered by date range
*/
function summary_page_callback() {
  $results = [
    "summary"=>[]
  ];

  $params = drupal_get_query_parameters();
  $start_date =$params['start_date'];
  $startdate = strtotime($start_date.'00:00:00');

  $end_date = $params['end_date'];
  $enddate = strtotime($end_date.'23:59:59');

  $common = new common();

  if($common->authenticate() == TRUE){

    $common = new common();

    $query = db_select('publication_date','p');
    $query->join('node','n','n.nid=p.nid');
    $query->innerJoin('field_data_field_authorized_user','f','n.nid=f.entity_id');
    $query->addField('p', 'nid','nid');
    $query->condition('p.published_at', $startdate,'>=');//oct 18 2015
    $query->condition('p.published_at', $enddate,'<=');//oct 18 2015
    $query->condition('n.type', 'job_offer');
    $privateJobsCount=$query->countQuery()->execute()->fetchField();

    $query = db_select('node','n');
    $query->join('publication_date','p','n.nid=p.nid');
    $query->innerJoin('field_data_field_authorized_user','f','n.nid=f.entity_id');
    $query->addField('p', 'nid','nid');
    $query->condition('p.published_at', $startdate,'>=');
    $query->condition('p.published_at', $enddate,'<=');//oct 18 2015
    $query->condition('n.type', 'government_jobs');
    $totalGovCount=$query->countQuery()->execute()->fetchField();

    $query = db_select('webform_submissions','ws');
    $query->addField('ws', 'nid');
    $query->condition('nid', $common->get_nid()); /*Node ID 15 specifies all the submissions related to jobs*/
    $query->condition('submitted', $startdate,'>=');
    $query->condition('submitted', $enddate,'<=');
    $totalapplications=$query->countQuery()->execute()->fetchField();//form submissions today

    $query = db_select('publication_date','p');
    $query->innerJoin('node','n','n.nid=p.nid');
    $query->innerJoin('field_data_field_authorized_user','f','p.nid=f.entity_id');
    $query->join('users','u','u.uid=f.field_authorized_user_uid');
    $query->addField('u', 'name','name');
    $query->addExpression('count(f.entity_id)','user_count');
    $query->addField('p', 'nid','nid');
    $query->condition('p.published_at', $startdate,'>=');//2019-12-23
    $query->condition('p.published_at', $enddate,'<=');//oct 18 2015
    $query->condition('n.type', array('job_offer','government_jobs'),'IN');
    $query->groupBy('u.name');
    $totalCountbyUser = $query->execute()->fetchAll();

    $query = db_select('publication_date','p');
    $query->innerJoin('node','n','n.nid=p.nid');
    $query->innerJoin('field_data_field_authorized_user','f','p.nid=f.entity_id');
    $query->join('users','u','u.uid=f.field_authorized_user_uid');
    $query->addField('n', 'title','title');
    $query->addField('u', 'name','name');
    $query->addField('p', 'nid','nid');
    $query->condition('p.published_at', $startdate,'>=');//2019-12-23
    $query->condition('p.published_at', $enddate,'<=');//oct 18 2015
    $query->condition('n.type', array('job_offer','government_jobs'),'IN');
    $allUrl = $query->execute()->fetchAll();

    $byUser = [];
    $urlArray=[];
    $obj = [
      "jobs_count_user"=>[],
      "Job_list"=>[
        "URL"=>[]
      ]
    ];
    $obj['jobs_count'] = $privateJobsCount+$totalGovCount;
    $obj['gov_jobs_count'] = $totalGovCount;
    $obj['pvt_jobs_count'] = $privateJobsCount;
    $obj['total_applications'] = $totalapplications;

    foreach ($allUrl as $url){
      $urlArray[$url->title] = url("node/$url->nid");
    }
    array_push($obj['Job_list']['URL'], current(array($urlArray)));

    foreach ($totalCountbyUser as $users) {
        $byUser[$users->name] = $users->user_count;
    }
    array_push($obj['jobs_count_user'], current(array($byUser)));
    array_push($results['summary'], $obj);

    return drupal_json_output($results);

  }
  else {
    http_response_code(401);
  }

}

/*
 * This function is to get all the course providers and details
 */
function course_providers_page_callback() {

  $common=new common();

  if($common->authenticate() == TRUE){


    /*
     * get employer ID's relevant to employer
    */
    $isEmployer = db_select('users_roles');
    $isEmployer->addField('users_roles', 'uid');
    $isEmployer->condition('rid', $common->get_course_rid());
    $providerID = $isEmployer->execute()->fetchCol();

    /*
     * employer Data
    */
    $query = db_select('users');
    $query->addField('users', 'uid','uid');
    $query->addField('users', 'name','name');
    $query->addField('users', 'mail','mail');
    $query->addField('users', 'picture','picture');
    $query->condition('uid', $providerID);

    $data = $query->execute()->fetchAll();
    $response = [
      'Providers' => []
    ];

    foreach ($data as $row) {

      $file = file_load($row->picture);
      $uri = $file->uri;
      $url = file_create_url($uri);

      $obj = [];
      $obj['uid'] = $row->uid;
      $obj['name'] = $row->name;
      $obj['mail'] = $row->mail;
      $obj['picture'] = $url;
      array_push($response['Providers'], $obj);

    }

    return drupal_json_output($response);
  }
  else
  {

    http_response_code(401);

  }

}

/*
 * This function is to get course details posted filtered by
 * date range
 */
function courses_page_callback() {

  $results = [];
  $params = drupal_get_query_parameters();
  $provider_id = $params['provider_id'];


  $start_date =$params['start_date'];
  $starttimestamp = strtotime($start_date.'00:00:00');

  $end_date = $params['end_date'];
  $endtimestamp = strtotime($end_date.'23:59:59');

  $common=new common();
  if($common->authenticate() == TRUE){

      $query = db_select('node', 'n');
      $query->join('node_expire', 'ne', 'n.nid=ne.nid');
      $query->addField('n', 'nid', 'nid');
      $query->addField('n', 'title', 'title');
      $query->addField('n', 'created', 'created');
      $query->addField('n', 'status', 'status');
      $query->addField('ne', 'expire', 'expire');
      $query->condition('n.uid', $provider_id);
      $query->condition('type', 'course');
      $query->condition('created', array($starttimestamp), '>=');
      $query->condition('created', array($endtimestamp), '<=');
      $data = $query->execute()->fetchAll();

      foreach ($data as $row) {

        $obj = [];
        $obj['nid'] = $row->nid;
        $obj['title'] = $row->title;
        $obj['created'] = $row->created;
        $obj['status'] = $row->status;
        $obj['expire'] = $row->expire;
        $obj['url'] = url("node/$row->nid");
        array_push($results, $obj);

      }
      return drupal_json_output($results);
      }

  else {
    http_response_code(401);
  }


}

/*
 * This function is to get course inquiries
 * filtered by date range by providing "course ID"
*/
function course_inquiry_page_callback() {
  $results = [];
  $params = drupal_get_query_parameters();
  $course_id = $params['course_id'];

  $start_date =$params['start_date'];
  $starttimestamp = strtotime($start_date.'00:00:00');

  $end_date = $params['end_date'];
  $endtimestamp = strtotime($end_date.'23:59:59');

  $common = new common();

  if($common->authenticate() == TRUE){
    if (isset($course_id)) {

      /*
       * Get application submissions
       */
      $query = db_select('webform_submitted_data');
      $query->addField('webform_submitted_data', 'sid');
      $query->condition('nid', $common->get_course_nid());
      $query->condition('data', $course_id);
      $query->condition('cid', $common->get_course_cid());
      $setofsid = $query->execute()->fetchAll();

      /*
       * Get taxonomy ID to identify the job industry
       */
      $query = db_select('field_data_field_course_category');
      $query->addField('field_data_field_course_category', 'field_course_category_tid');
      $query->condition('entity_id', $course_id);
      $tid = $query->execute()->fetchAll();//get taxanomy ID

      foreach ($tid as $tidValue) {

        /*
         * Get industry name based on taxanomy ID
         */
        $query2 = db_select('taxonomy_term_data');
        $query2->addField('taxonomy_term_data', 'name');
        $query2->condition('tid', $tidValue->field_industry_tid);
        $result2 = $query2->execute()->fetchAll();
      }

      if ($setofsid) {
        foreach ($setofsid as $sid) {
          /*
           * Get all data relevant to application based on submission ID
           */
          $querySubmissions = db_select('webform_submitted_data', 'wsd');
          $querySubmissions->join('webform_submissions', 'sd', 'sd.sid=wsd.sid');
          $querySubmissions->leftJoin('webform_component', 'wc', 'wsd.cid = wc.cid');
          $querySubmissions->addField('wsd', 'data');
          $querySubmissions->addField('wsd', 'sid');
          $querySubmissions->addField('wc', 'name');
          $querySubmissions->condition('wc.nid', '16122');
          $querySubmissions->condition('wsd.sid', $sid->sid);
          $querySubmissions->condition('sd.sid', $sid->sid);
          $querySubmissions->condition('submitted', array($starttimestamp), '>=');
          $querySubmissions->condition('submitted', array($endtimestamp), '<=');
          $querySubmissions->groupBy('wsd.data');
          $result = $querySubmissions->execute()->fetchAll();

          foreach ($result as $row) {
              $obj['id'] = $row->sid;
              $obj[$row->name] = $row->data;
              foreach ($result2 as $jobCategory){
                $obj['job_category']=$jobCategory->name;
              }
          }
          array_push($results, $obj);
        }

      }
      if($obj == NULL)
      {
        $empty=[
          "course_inquiry:"=>[]
        ];
        return drupal_json_output($empty);
      }else
      {
        return drupal_json_output($results);
      }

    }
    else {
      http_response_code(412);
    }
  }
  else {
    http_response_code(401);
  }

}


/*
 * This function is to get data from forms
 * //17467 form ID is for overseas form
*/
function overseas_page_callback() {
  $params = drupal_get_query_parameters();
  $formid =$params['form_id'];

  $results=[];

  $common = new common();

  if($common->authenticate() == TRUE){
    if (isset($formid)) {

      /*
       * Get overseas data submissions
       */
      $query = db_select('webform_submitted_data');
      $query->addField('webform_submitted_data', 'sid');
      $query->condition('nid', $formid);
      $setofsid = $query->distinct()->execute()->fetchAll();

      if ($setofsid) {
        foreach ($setofsid as $sid) {
          /*
           * Get all data relevant to application based on submission ID
           */
          $query = db_select('webform_submitted_data', 'wsd');
          $query->join('webform_submissions', 'sd', 'sd.sid=wsd.sid');
          $query->leftJoin('webform_component', 'wc', 'wsd.cid = wc.cid');
          $query->addField('wsd', 'data');
          $query->addField('wsd', 'sid');
          $query->addField('wc', 'name');
          $query->condition('wc.nid', $formid);
          $query->condition('wsd.sid', $sid->sid);
          $query->condition('sd.sid', $sid->sid);
          $query->groupBy('wsd.data');
          $result = $query->execute()->fetchAll();

          foreach ($result as $row)
          {
            if ($row->name == 'Attach your CV') {
              $file = file_load($row->data);
              $obj[$row->name] = file_create_url($file->uri);
            }
            else if($row->name != 'Attach your CV/t') {
              $obj['id'] = $row->sid;
              $obj[$row->name] = $row->data;
            }
          }
          array_push($results, $obj);
        }
      }
      if ($obj == NULL) {
        $empty = [
          "overseas_applications:" => []
        ];
        return drupal_json_output($empty);
      }
      else {
        return drupal_json_output($results);
      }
    }
    else{
      http_response_code(412);
    }
  }
  else {
    http_response_code(401);
  }
}



function agent_page_callback() {

  $common=new common();

  if($common->authenticate() == TRUE){

    /*
     * get employer ID's relevant to employer
    */
    $isAgent = db_select('users_roles');
    $isAgent->addField('users_roles', 'uid');
    $isAgent->condition('rid', '7');
    $agentID = $isAgent->execute()->fetchCol();

    /*
     * employer Data
    */
    $query = db_select('users');
    $query->addField('users', 'uid','uid');
    $query->addField('users', 'name','name');
    $query->addField('users', 'mail','mail');
    $query->condition('uid', $agentID);

    $data = $query->execute()->fetchAll();
    $response = [
      'Agents' => []
    ];

    foreach ($data as $row) {

      $obj = [];
      $obj['uid'] = $row->uid;
      $obj['name'] = $row->name;
      $obj['mail'] = $row->mail;
      array_push($response['Agents'], $obj);

    }

    return drupal_json_output($response);
  }
  else
  {

    http_response_code(401);

  }

}


/**
 * Page callback: drupal api settings
 * Created for configuration form
 * @see drupal_api_menu()
 */
function drupal_api_form($form, &$form_state) {

  $query = db_select('api_configuration');
  $query->addField('api_configuration', 'api_key');
  $query->addField('api_configuration', 'nid');//15
  $query->addField('api_configuration', 'rid');//4
  $query->addField('api_configuration', 'cid');//10
  $query->addField('api_configuration', 'courses_nid');
  $query->addField('api_configuration', 'courses_rid');
  $query->addField('api_configuration', 'courses_cid');

  $output = $query->execute()->fetchAll();

  foreach ($output as $result){
    $api_key=$result->api_key;
    $nid=$result->nid;
    $rid=$result->rid;
    $cid=$result->cid;
    $courses_nid=$result->courses_nid;
    $courses_rid=$result->courses_rid;
    $courses_cid=$result->courses_cid;

  }

  $form['form_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API key'),
    '#default_value' => $api_key,
    '#description' => t('API key for webform'),
    '#required' => TRUE,
  );
  $form['form_node_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Node ID'),
    '#default_value' => $nid,
    '#description' => t('Node ID for webform'),
    '#required' => TRUE,
  );

  $form['form_rid'] = array(
    '#type' => 'textfield',
    '#title' => t('RID'),
    '#default_value' => $rid,
    '#description' => t('RID for webform'),
    '#required' => TRUE,
  );
  $form['form_cid'] = array(
    '#type' => 'textfield',
    '#title' => t('CID'),
    '#default_value' => $cid,
    '#description' => t('CID for webform'),
    '#required' => TRUE,
  );

  $form['form_course_nid'] = array(
    '#type' => 'textfield',
    '#title' => t('Course NID'),
    '#default_value' => $courses_nid,
    '#description' => t('NID for course'),
    '#required' => TRUE,
  );

  $form['form_course_rid'] = array(
    '#type' => 'textfield',
    '#title' => t('Course RID'),
    '#default_value' => $courses_rid,
    '#description' => t('RID for course'),
    '#required' => TRUE,
  );

  $form['form_course_cid'] = array(
    '#type' => 'textfield',
    '#title' => t('Course CID'),
    '#default_value' => $courses_cid,
    '#description' => t('CID for course'),
    '#required' => TRUE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );


  return $form;
}

/**
 * Validate configuration form
 * @see drupal_api_menu()
 */
function drupal_api_form_validate($form, &$form_state) {
  if ($form_state['values']['form_api_key'] == ""){
    form_set_error('api_key', t('API key Cannot Be empty.'));
  }

}

/**
 * Save configuration form data to custom table "api_configuration"
 * @see drupal_api_menu()
 */
function drupal_api_form_submit($form, &$form_state) {

  $query = db_select('api_configuration');
  $query->addField('api_configuration', 'id');
  $output = $query->execute()->fetchField();

  if(empty($output)) {

    $query = db_insert('api_configuration')
      ->fields([
        'api_key' => $form_state['values']['form_api_key'],
        'nid' => $form_state['values']['form_node_id'],
        'rid' => $form_state['values']['form_rid'],
        'cid' => $form_state['values']['form_cid'],
        'courses_nid' => $form_state['values']['form_course_nid'],
        'courses_rid' => $form_state['values']['form_course_rid'],
        'courses_cid' => $form_state['values']['form_course_cid'],

      ])
      ->execute();
    drupal_set_message("Successfully inserted");
  }
  else{

    $query = db_update('api_configuration')
      ->fields([
        'api_key' => $form_state['values']['form_api_key'],
        'nid' => $form_state['values']['form_node_id'],
        'rid' => $form_state['values']['form_rid'],
        'cid' => $form_state['values']['form_cid'],
        'courses_nid' => $form_state['values']['form_course_nid'],
        'courses_rid' => $form_state['values']['form_course_rid'],
        'courses_cid' => $form_state['values']['form_course_cid'],

      ])
      ->execute();
    drupal_set_message("Successfully updated");

  }


}
?>
